name: Test & Deploy Docs
on: [push, pull_request]
permissions:
    contents: read
    pages: write
    id-token: write
    deployments: write
jobs:
    test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js from .nvmrc
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
            - name: Run prettier
              run: npm run prettier.check
            - name: Run tests
              run: npm run test.unit
            - name: Clean tree
              run: npm run test.clean-tree
    build:
        runs-on: ubuntu-20.04
        needs: test
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js from .nvmrc
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - name: Cache build outputs
              id: build-output
              uses: actions/cache@v3
              with:
                  path: build/docs
                  key: build-output-${{ github.run_id }}
            - name: Build all
              run: npm run build
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
            - name: Build docs
              run: npm run docs
            - name: copy-to-docs
              run: cp -r build/app/ build/docs/app
    deploy:
        runs-on: ubuntu-20.04
        needs: build
        if: ${{ github.ref == 'refs/heads/main' }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js from .nvmrc
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Cache build outputs
              id: build-output
              uses: actions/cache@v3
              with:
                  path: build/docs
                  key: build-output-${{ github.run_id }}
            - name: Setup Github Pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: build/docs
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
